### ISSUE TITLE
EVDS düzenlemesi gereği API key'in URL'den request header içine alınması

### ISSUE THREAD

**Issue by ThoAppelsin** [fatihmete/evds#15]
EVDS'nin yeni düzenlemesi gereği API key'in URL üzerinden değil, request header üzerinden iletilmesi gerekli. 5-25 Nisan 2024 tarihleri arasında eski (mevcut) ve yeni yöntem beraberce kullanılabilir olacak. Ancak 26 Nisan 2024 itibariyle eski yöntem kullanılamaz olacak. EVDS'den gelen mesajı iliştiriyorum:

> Sayın ilgili,
> 
> Eğer EVDS (https://evds2.tcmb.gov.tr/) web servis kullanıcısı iseniz aşağıdaki duyuru sizi ilgilendiriyor.
> 
> Önceki duyurumuzda EVDS nin web servis parametrelerinde güvenlik sebebiyle bir düzenleme yapılacağını belirtmiştik.
> 
> URL adresinden giden “key” parametresinin artık http request header içinde gelmesi ve web servis kullanan uygulamalarınızda “key=xxxxxx” parametresini http request header olarak dönüştürmeniz gerektiği belirtilmişti.
> 
> Bu düzenleme 05 Nisan 2024 Cuma saat 21:00 TSİ tarihinden itibaren geçerli olacaktır.
> 
> Kullanıcılara, değişikliği test etme olanağının sağlanması amacıyla, halen kullanılan uygulama 25 Nisan 2024 Perşembe saat 21:00 TSİ ye kadar yeni uygulama ile birlikte kullanılabilir olacaktır.
> 
> 26 Nisan 2024 Cuma gününden itibaren sadece yeni sürüm kullanılabilecektir.
> 
> Tüm web servis kullanıcılarına duyurulur.
> 
> İyi çalışmalar dileriz.
> 
> EVDS grubu
> 
> E-posta: [yeniEVDS@tcmb.gov.tr](mailto:yeniEVDS@tcmb.gov.tr)

**Comment by fatihmete** [comment]
[PR #16](https://github.com/fatihmete/evds/pull/16) ile gerekli guncelleme yapilip, pypi repolarinda paket guncellenmistir.

**Comment by berkaycapar** [comment]
bilgi için teşekkürler
