### ISSUE TITLE
EVDS Connection Error alıyorum

### ISSUE THREAD

**Issue by Gormezoglu** [fatihmete/evds#9]
Merhabalar,

TCMB Python API ile çalışmak için

```python
from evds import evdsAPI
evds = evdsAPI(keys.CBRT_API)
``` 

kod blokunu çalıştırdığımda 

**Main categories couldn't load. Please check your API Key.** uyarısı alıyorum. 
API keyi kontrol ettim ve bir hata yok. Acaba API ulaşmak için başka bir authorization süreci mi çalıştırmam lazım ? 
Cevap için şimdiden teşekkür ederim.

**Comment by fatihmete** [comment]
Merhaba,
Kontrol ettiğimde bir hata almadan bağlantı sağlanabiliyor. API key dışında bir yetki süreci gerekmiyor. Kullandığınız python sürümünü paylaşabilir misiniz?

**Comment by Gormezoglu** [comment]
Python 3.10.8 kullanıyorum. API key'i copy paste ile quote içinde quote'suz şekilde denedim. Aynı hatayı almaya devam ediyorum

**Comment by fatihmete** [comment]
Sorun pandas kütüphanesinin güncellenmesinden kaynaklanmakta. API tarafından numeric değerler string olarak gönderiliyor. Bunlar DataFrame'e dönüştürülürken float veya int'e dönüştürülüyor. Pandas bu durumda uygun olmayan bir veri tipi ile karşılaşırsa uyarı veriyordu. Ancak güncelleme ile bu dönüştürme işleminde uygun olmayan bir değer geldiğinde hata vermeye başlamış. Yeni sürüme (0.3.0) bu hatanın çözümü eklenecek. Geçici bir çözüm olarak aşağıdaki şekilde pandas sürümünü düşürebilirsiniz.

```
pip install pandas==1.5.3
```

**Comment by Gormezoglu** [comment]
Çok teşekkür ederim. 

Bu arada yeni sürümün geleceğini öğrenmek sevindirdi.

**Comment by fatihmete** [comment]
Aşağıdaki komut ile paketi güncelleyip tekrar deneyebilir misiniz?
```
pip install evds --upgrade
```

**Comment by Gormezoglu** [comment]
Hocam bu sefer geldi veriler.

Teşekkür ederim desteğiniz için.
